// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAe43vbqtN-cGsdpK6EtYRNJKLEAnuGXj8',
    appId: '1:167373182132:web:4f82307856943b45bef3e1',
    messagingSenderId: '167373182132',
    projectId: 'mobileappdev2024',
    authDomain: 'mobileappdev2024.firebaseapp.com',
    databaseURL: 'https://mobileappdev2024-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobileappdev2024.appspot.com',
    measurementId: 'G-5P1FEW6SW7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC15dEu4mbKDFCm_XCEtbXmE6Me4e6XJrc',
    appId: '1:167373182132:android:b6a82a21ac836e5bbef3e1',
    messagingSenderId: '167373182132',
    projectId: 'mobileappdev2024',
    databaseURL: 'https://mobileappdev2024-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobileappdev2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFgKZfOQ_M2vILs_qk-uMfpX52ehqEXIk',
    appId: '1:167373182132:ios:8f29b7ca1c1f4d05bef3e1',
    messagingSenderId: '167373182132',
    projectId: 'mobileappdev2024',
    databaseURL: 'https://mobileappdev2024-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobileappdev2024.appspot.com',
    iosBundleId: 'com.example.maneeStatesDemos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFgKZfOQ_M2vILs_qk-uMfpX52ehqEXIk',
    appId: '1:167373182132:ios:7dcd4f9f897b246fbef3e1',
    messagingSenderId: '167373182132',
    projectId: 'mobileappdev2024',
    databaseURL: 'https://mobileappdev2024-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mobileappdev2024.appspot.com',
    iosBundleId: 'com.example.maneeStatesDemos.RunnerTests',
  );
}
